### ISSUE TITLE
ClusterIP service type doesn't work for proxy

### ISSUE THREAD

**Issue by kanya-approve** [jeremylvln/Shulker#152]
### What happened?

If you create a ProxyFleet with the service type of ClusterIP, a service is not created.

`apiVersion: shulkermc.io/v1alpha1
kind: ProxyFleet
metadata:
  name: public
spec:
  clusterRef:
    name: getting-started
  replicas: 1
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
  template:
    spec:
      version:
        channel: Velocity
        name: latest
      config: {}`

### What components are involved in your issue?

Operator

### Version

master

### Kubernetes Version

1.26.9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremylvln** [comment]
The issue should be fixed, please be aware that with `ClusterIP`, you should not fill the `externalTrafficPolicy` (remove it entirely)
