### ISSUE TITLE
Add the possibility to use custom server jars

### ISSUE THREAD

**Issue by jeremylvln** [jeremylvln/Shulker#253]
### Discussed in https://github.com/jeremylvln/Shulker/discussions/252

<div type='discussions-op-text'>

<sup>Originally posted by **TropicLegend** November 30, 2023</sup>
It would be very beneficial to have the ability to use custom server jars since only paper or folia feels limiting</div>

**Comment by TropicLegend** [comment]
It unfortunately does not work on my end: https://github.com/jeremylvln/Shulker/pull/254#issuecomment-1836143627
