### ISSUE TITLE
Helm chart in CD(ArgoCD) doesn't update shulker operator

### ISSUE THREAD

**Issue by Svetch** [jeremylvln/Shulker#345]
### What happened?

I've encountered an issue where the Shulker operator's version does not update as expected. The root of the problem appears to be that while the application version of Shulker is updated, the corresponding Helm chart version remains unchanged. This discrepancy causes ArgoCD to cache the older version of the chart, preventing it from downloading the updated version when only the app version is revised. Currently one method to woraround this, you need to update not only the chart version but the container tag too.

## Expected Behavior:
Ideally, whenever a new version of Shulker is released, there should be a concurrent release of a new Helm chart reflecting this updated version. This would streamline the continuous deployment (CD) pipeline process, as it would only necessitate updating the chart version to incorporate the latest changes from Shulker. This approach ensures that both the application and its deployment mechanisms are in sync, facilitating a smoother update process within the CD pipeline.

### What components are involved in your issue?

Operator

### Version

0.5.3

### Kubernetes Version

1.28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremylvln** [comment]
Hi!

Sorry I missed the notification on this issue, my bad.

I see what the issue is, I will try to see how I can manage to fix that. Thanks for the report!

**Comment by jeremylvln** [comment]
I've modified the release process to set the chart version the same as the app, as they are co-located and updated at the same time. I've published manually the Helm chart to avoid having to create a new release:

```
$ helm search repo shulker -l
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                                       
shulker/shulker-operator        0.5.3           0.5.3           A Kubernetes operator for managing complex and ...
shulker/shulker-operator        0.1.0           0.5.3           A Kubernetes operator for managing complex and ...
```

Confirm me that everything is good for you :)

**Comment by Svetch** [comment]
Yes its work fine. Thanks!
