### ISSUE TITLE
 MountVolume.SetUp failed for volume "agones-allocator-client-tls" : secret "allocator-client.default" not found

### ISSUE THREAD

**Issue by Ianzhao071102** [jeremylvln/Shulker#377]
### What happened?

![image](https://github.com/jeremylvln/Shulker/assets/111406943/7b977674-1d89-44df-88f7-ed9e44aa2164)
The mount secret is not found. it also isn't defined in agones' yaml nor shulkers' yaml file

### What components are involved in your issue?

Operator

### Version

0.6.0

### Kubernetes Version

1.28.2

### Relevant log output

```Shell
Just The Event:
MountVolume.SetUp failed for volume "agones-allocator-client-tls" : secret "allocator-client.default" not found
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by jeremylvln** [comment]
Hi,

Please follow the installation instructions on the documentation, you missed the part where you need to configure Agones properly for these certificates to be generated: https://shulker.jeremylvln.fr/latest/guide/getting-started/prerequisites.html#agones

**Comment by Ianzhao071102** [comment]
I did this: 

to make a agones yaml file
```
helm pull --untar https://agones.dev/chart/stable/agones-1.37.0.tgz
pause
cd agones
pause
helm template agones --namespace agones-system  .  --set agones.controller.generateTLS=false  --set agones.allocator.generateTLS=false --set agones.allocator.generateClientTLS=false --set agones.crds.cleanupOnDelete=false --set agones.featureGates="PlayerTracking=true" --set agones.allocator.service.serviceType=ClusterIP --set "gameservers.namespaces={shulker-system}"  > agones.yaml 
pause
```

and applied it server side     

so idk why this is still happening, the shulker's everything is applied to the namespace called *shulker-system*
and all agones stuff running smooth

**Comment by Ianzhao071102** [comment]
sorry, i am not being careful
 --set agones.controller.generateTLS=true  --set agones.allocator.generateTLS=true --set agones.allocator.generateClientTLS=true 
sorry for the interrupt

**Comment by jeremylvln** [comment]
There is no problem asking for help :)
Do not hesitate !

Thanks!
