### ISSUE TITLE
Ability to override Agent download

### ISSUE THREAD

**Issue by jeremylvln** [jeremylvln/Shulker#478]
### Discussed in https://github.com/jeremylvln/Shulker/discussions/477

<div type='discussions-op-text'>

<sup>Originally posted by **TehNeon** March 22, 2024</sup>
It would be nice to have some way to either disable the download of the agent or a way to change the source of the download. The reasoning I propose this is that I'm building my own server images that have plugins baked into it (and proxy/paper jars) to prevent having to downloading assets from external sources. I'm also struggling from either my ISP or the repository host throttling my connection on downloading the agent causing it to take around 5 minutes just to finish the init-fs container on pod initialization. </div>

**Comment by TehNeon** [comment]
I just rolled these changes out to my cluster and it appears now the `init-fs` container fails. It appears it fails regardless of modifying the newly added `skipAgentDownload` configuration. It does appear the agent skipping logic does work though based on turning it on/off, but in both cases the following errors occur. 

ProxyFleet:
```
/mnt/shulker/config/init-fs.sh: line 15: SHULKER_PROXY_PLUGIN_URLS: parameter not set
```
MinecraftServerFleet:
```
/mnt/shulker/config/init-fs.sh: line 13: SERVER_WORLD_URL: parameter not set
```

**Comment by jeremylvln** [comment]
Fixed in last commit. Very sorry for the trouble.
