### ISSUE TITLE
No limbo server found

### ISSUE THREAD

**Issue by Josscoder** [jeremylvln/Shulker#611]
### What happened?

Hi, I wanted to report this. I don't know if it's my mistake, but I have the limbo pod and lobby and when I log in it tells me that a limbo server is not found.

![image](https://github.com/user-attachments/assets/647769eb-fa57-4196-be54-a35900c74725)
![image](https://github.com/user-attachments/assets/e8b0ba68-d826-4ed3-aa3c-8f6dfd2caf71)
![image](https://github.com/user-attachments/assets/e8168d40-a943-439a-8016-a3f433fe41bc)

### What components are involved in your issue?

Proxy Agent (Velocity)

### Version

0.8.1

### Kubernetes Version

v1.29.6+k3s2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Josscoder** [comment]
![image](https://github.com/user-attachments/assets/2a85466d-cee5-4ca4-ad8f-63311f0e7ff9)

**Comment by DiogoMurano** [comment]
same

**Comment by DiogoMurano** [comment]
I found the solution. This happens because shulker does not seem to be compatible with the latest agones updates.

I managed to solve my problem by installing agones version 1.39
helm install agones agones/agones --version 1.39.0 --namespace agones-system --create-namespace

**Comment by jeremylvln** [comment]
Hi,

The fix will soon be merged, I'll make a quick test tour and will publish a new release. Thanks a lot for your patience :)

**Comment by jeremylvln** [comment]
Hi,

This is now fixed starting from 0.9.0. However, due to a crash in this version, I advise you to move to 0.10.0 directly.

Thanks!
