### ISSUE TITLE
Set up problem

### ISSUE THREAD

**Issue by Rynf0rce** [jeremylvln/Shulker#640]
I have solved this problem thx u >ㅅ<

```
helm upgrade --install agones agones/agones \\n--namespace agones-system \\n--set 'gameservers.namespaces={default,shulker-system}' \\n--set agones.allocator.install=true \\n--set agones.allocator.service.serviceType=ClusterIP
```

Thank you for your kind response

I was so fascinated by the idea of implementing Minecraft with Agones that I decided to back it.

Personally, I would love to do what you've created in EKS, one by one, but I've run into another problem.

~I ran the yaml file found here https://shulker.jeremylvln.fr/latest/guide/getting-started/your-first-cluster.html#a-spoon-of-minecraftcluster on my K8S and faced the error PreBind plugin “VolumeBinding”: binding volumes running on data-getting-started-redis-managed-0.~

I want to implement VolumeBinding with EFS, but I'm not sure how to do it... Or if that's not possible, what can I do with EBS?

The reason why we want to use EFS, which is easy to understand if you know anything about minifarms, is that we want to have one markserver per user to reflect their world information.

~[23:52:01 WARN] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Fleet's external address was not found, the Service may not be ready yet or is not a LoadBalancer~

<img width="1196" alt="Screenshot 2024-08-30 at 9 00 38" src="https://github.com/user-attachments/assets/f484810b-d802-4e2a-a36d-22691329b910">

<img width="844" alt="Screenshot 2024-08-30 at 9 01 26" src="https://github.com/user-attachments/assets/835d7d87-2881-4e4c-aede-c21415cde4ce">

![Screenshot 2024-08-30 at 10 29 18](https://github.com/user-attachments/assets/af80cab1-ea0d-4e87-8350-8e5b4490fc2b)

<img width="430" alt="Screenshot 2024-08-30 at 10 30 12" src="https://github.com/user-attachments/assets/0b15adbf-283c-4bc2-8ed5-5615df20b105">

<img width="662" alt="Screenshot 2024-08-30 at 10 30 25" src="https://github.com/user-attachments/assets/e14f6090-6f2b-4b5e-b3a6-53f64f5546cf">

<img width="803" alt="Screenshot 2024-08-30 at 10 31 14" src="https://github.com/user-attachments/assets/efc1badf-3a5a-49fa-8e08-cdfaf4337e7e">

EKS Cluster is located in Public Subnet

__After lauching minecraftserver.yaml, I wasn't able to join my mc server. Just in case, I tried again, but I can't connect to the server.__

<img width="1032" alt="Screenshot 2024-08-30 at 12 20 13" src="https://github.com/user-attachments/assets/d6ceaa88-023a-48f8-b398-aeaafc750518">
<img width="622" alt="Screenshot 2024-08-30 at 12 21 45" src="https://github.com/user-attachments/assets/beac6198-9c50-4af4-8bf9-050b77b740f0">

kubectl describe pod -n shulker-tutorial public-fvfc2-7579z
<img width="1166" alt="Screenshot 2024-08-30 at 16 11 02" src="https://github.com/user-attachments/assets/801a6669-5cf1-45f4-820d-e34836ec155e">

<img width="876" alt="Screenshot 2024-08-31 at 19 46 50" src="https://github.com/user-attachments/assets/19abc1cf-cd01-46f7-bd0e-44b9c587835b">
> Can't mount /tmp/drain-lock

I don't understand Agones or your project very well yet, so I have some additional questions.

I haved checked agones example (https://agones.dev/site/docs/examples/supertuxkart/) activated

When creating a minecraft server, is it possible to give the server and port number statically? And how does match making work in your project?

Sorry for asking so many questions at the beginning, but I'm very fascinated by your project.

If you are sensitive about what I write here, you can contact me on Discord (speedcore300 / Speedcore#3923).

_Originally posted by @Rynf0rce in https://github.com/jeremylvln/Shulker/discussions/637#discussioncomment-10492307_

**Comment by jeremylvln** [comment]
Let's continue in the discussion and keep the issue for bugs & feature requests
